generate:
  - types
  - client
accessModifier: public
typeOverrides:
  schemas:
    NullableEnergyLevel: Components.Schemas.EnergyLevel
    ActivitySeriesUpdateRequest: KairoActivitySeriesUpdateRequest
    ActivityOccurrencePatchRequest: KairoActivityOccurrencePatchRequest
    TaskUpdateRequest: KairoTaskUpdateRequest
    TagUpdateRequest: KairoTagUpdateRequest
    RoutineUpdateRequest: KairoRoutineUpdateRequest
